# ~/.config/helix/themes/wave.toml
inherits = "default"

# UI Elements
"ui.background" = { bg = "#1f1f28" }                            # sumiInk3
"ui.text" = { fg = "#dcd7ba" }                                  # fujiWhite
"ui.text.focus" = { fg = "#dcd7ba", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "#c8c093" }                         # oldWhite
"ui.cursor" = { fg = "#1f1f28", bg = "#dcd7ba" }                # inverted
"ui.cursor.insert" = { modifiers = ["underlined"] }
"ui.cursor.select" = { bg = "#2d4f67" }                         # waveBlue1
"ui.cursor.match" = { modifiers = ["underlined"] }
"ui.selection" = { bg = "#2d4f67" }                             # waveBlue1
"ui.gutter" = { bg = "#16161d" }                                # sumiInk4
"ui.linenr" = { fg = "#727169" }                                # sumiInk6
"ui.linenr.selected" = { fg = "#dcd7ba", modifiers = ["bold"] } # fujiWhite
"ui.statusline" = { fg = "#dcd7ba", bg = "#16161d" }            # fujiWhite, sumiInk4
"ui.statusline.inactive" = { fg = "#727169", bg = "#16161d" }   # sumiInk6, sumiInk4
"ui.statusline.insert" = { fg = "#dcd7ba", bg = "#16161d" }
"ui.statusline.select" = { fg = "#dcd7ba", bg = "#2d4f67" }
"ui.virtual.whitespace" = { fg = "#54546d" }                    # sumiInk6
"ui.virtual.indent-guide" = { fg = "#363646" }                  # sumiInk2
"ui.menu" = { fg = "#dcd7ba", bg = "#223249" }                  # fujiWhite, waveBlue1
"ui.menu.selected" = { fg = "#dcd7ba", bg = "#363646" }         # fujiWhite, sumiInk2
"ui.window" = { fg = "#54546d" }                                # sumiInk6
"ui.popup" = { bg = "#0f0f14" }                                 # sumiInk0
"ui.help" = { fg = "#dcd7ba", bg = "#0f0f14" }                  # fujiWhite, sumiInk0

# Syntax Highlighting
"attribute" = { fg = "#7e9cd8" }                       # crystalBlue
"comment" = { fg = "#727169", modifiers = ["italic"] } # fujiGray
"constant" = { fg = "#ffa066" }                        # surimiOrange
"constant.builtin" = { fg = "#ffa066" }                # surimiOrange
"constant.builtin.boolean" = { fg = "#ffa066" }        # surimiOrange
"constructor" = { fg = "#7e9cd8" }                     # crystalBlue
"function" = { fg = "#7e9cd8" }                        # crystalBlue
"function.builtin" = { fg = "#7e9cd8" }                # crystalBlue
"function.method" = { fg = "#7e9cd8" }                 # crystalBlue
"keyword" = { fg = "#957fb8" }                         # oniViolet
"operator" = { fg = "#e6c384" }                        # boatYellow2
"string" = { fg = "#98bb6c" }                          # springGreen
"type" = { fg = "#7fb4ca" }                            # waveAqua2
"variable" = { fg = "#dcd7ba" }                        # fujiWhite
"variable.builtin" = { fg = "#c34043" }                # waveRed
"variable.parameter" = { fg = "#b8b4d0" }              # oniViolet2
"punctuation" = { fg = "#9cabca" }                     # springViolet2
"punctuation.delimiter" = { fg = "#9cabca" }           # springViolet2
"punctuation.bracket" = { fg = "#9cabca" }             # springViolet2

# Markup
"markup.heading" = { fg = "#c34043", modifiers = ["bold"] }        # waveRed
"markup.list" = { fg = "#ffa066" }                                 # surimiOrange
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "#7e9cd8" }                                 # crystalBlue
"markup.link.url" = { fg = "#7e9cd8", modifiers = ["underlined"] }
"markup.raw" = { fg = "#98bb6c" }                                  # springGreen

# Diagnostics
"error" = { fg = "#c34043" }                                         # waveRed
"warning" = { fg = "#e6c384" }                                       # boatYellow2
"info" = { fg = "#658594" }                                          # dragonBlue
"hint" = { fg = "#6a9589" }                                          # waveAqua1
"diagnostic" = { underline = { color = "#c34043", style = "curl" } } # waveRed

# Diff
"diff.plus" = { fg = "#98bb6c" }  # springGreen
"diff.minus" = { fg = "#c34043" } # waveRed
"diff.delta" = { fg = "#7e9cd8" } # crystalBlue

# Palette
[palette]
sumiInk0 = "#0f0f14"
sumiInk1 = "#16161d"
sumiInk2 = "#363646"
sumiInk3 = "#1f1f28"
sumiInk4 = "#16161d"
sumiInk5 = "#2a2a37"
sumiInk6 = "#54546d"
fujiWhite = "#dcd7ba"
oldWhite = "#c8c093"
fujiGray = "#727169"
waveBlue1 = "#2d4f67"
waveBlue2 = "#223249"
crystalBlue = "#7e9cd8"
springBlue = "#6a9589"
springViolet1 = "#938aa9"
springViolet2 = "#9cabca"
springGreen = "#98bb6c"
waveAqua1 = "#6a9589"
waveAqua2 = "#7fb4ca"
oniViolet = "#957fb8"
oniViolet2 = "#b8b4d0"
boatYellow1 = "#e6c384"
boatYellow2 = "#e6c384"
surimiOrange = "#ffa066"
carpYellow = "#e6c384"
sakuraPink = "#d27e99"
waveRed = "#c34043"
peachRed = "#e82424"
samuraiRed = "#e82424"
roninYellow = "#ff9e3b"
dragonBlue = "#658594"
katanaGray = "#717c7c"
autumnGreen = "#76946a"
autumnRed = "#c34043"
autumnYellow = "#dca561"
winterGreen = "#2b3328"
winterRed = "#43242b"
winterBlue = "#252535"
winterYellow = "#49443c"
