[[language]]
name = "go"
auto-format = true
formatter = { command = "gofmt" }
language-servers = ["gopls", "golangci-lint-lsp", "harper-ls"]

[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["+nightly"] }
auto-format = true
language-servers = ["rust-analyzer", "harper-ls"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
language-servers = ["taplo", "tombi", "harper-ls"]

[[language]]
name = "jsonc"
auto-format = true
indent = { tab-width = 4, unit = "    " }


################################# TS/JS SHIT#######################################

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.eslint]
command = "/opt/homebrew/bin/vscode-eslint-language-server"
args = ["--stdio"]

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.eslint.config]
nodePath = ""
# onIgnoredFiles = "off"
# packageManager = "npm"
quiet = false
rulesCustomizations = []
run = "onType"
# useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
experimental = { useFlatConfig = false }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

########################### TS/TSX ########################
[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  # "vscode-eslint-language-server",
  "eslint",
  "harper-ls",
]
auto-format = true
roots = ["eslint.config.mjs"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  # "vscode-eslint-language-server",
  "eslint",
  "harper-ls",
  "tailwindcss-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

#############################  JS/JSX ################
[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "eslint",
  "harper-ls",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "eslint",
  "harper-ls",
  "tailwindcss-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true


# [language-server.eslint.config]
# codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
# format = { enable = true }
# nodePath = ""
# quiet = false
# rulesCustomizations = []
# run = "onType"
# validate = "on"
# experimental = {}
# problems = { shortenToSingleLine = false }

############################# HARPER ################
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
